Jun 20 03:25:08 hostname1 logrotate: ALERT exited abnormally with [2]
Jun 20 03:25:09 hostname1 run-parts(/etc/cron.daily)[20448]: finished logrotate
Jun 20 03:26:21 hostname1 anacron[28963]: Job 'cron.daily' terminated
Jun 20 03:26:22 hostname1 anacron[28963]: Normal exit (1 job run)
Jun 20 03:30:01 hostname1 CROND[31463]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Jun 20 03:30:01 hostname1 CROND[31462]: (root) CMD (/var/system/bin/sys-cmd -F > /dev/null 2>&1)
Jun 20 03:30:09 hostname1 CROND[31462]: (root) CMD (/var/system/bin/sys-cmd -F > /dev/null 2>&1)
